# Generated by Django 3.2.7 on 2021-09-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0003_auto_20210923_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
