# Generated by Django 3.2.7 on 2021-09-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0004_video_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Influencer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation_name',
        ),
    ]
