# Generated by Django 3.2.7 on 2021-09-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0005_auto_20210924_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='review',
        ),
    ]
