# Generated by Django 3.2.7 on 2021-09-25 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0006_auto_20210924_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='analysed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='user_likes',
            field=models.ManyToManyField(related_name='all_like', to='reels.User'),
        ),
        migrations.AlterField(
            model_name='video',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc', to='reels.user'),
        ),
    ]
