# Generated by Django 3.2.7 on 2021-09-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_rename_user_ecommerce_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('T', 'Trouser')], max_length=2, null=True),
        ),
    ]
